import { FieldValues, useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'

const schema = z.object({
    email: z.string().email({ message: 'Please enter a valid email address.' }),
    password: z.string().min(8, {
        message: 'The password must be at least eight characters long.'
    })
})

type FormData = z.infer<typeof schema>

const App = () => {
    const {
        //the register object is used to register the input fields with react-hook-form, allowing it to track their values and validation status. it contains methods and properties that facilitate the integration of form inputs with the form handling logic provided by react-hook-form. This `register` is used to connect the email and password input fields to the form state and validation logic defined by the schema. The order of the properties in the destructuring assignment is not important, but it is common to list `register` first as it is often the most frequently used property when working with forms in react-hook-form.
        register,
        //handleSubmit is a higher-order function that wraps the form submission handler. it validates all registered fields against the zod schema before executing the submission callback. if validation passes, it calls the provided function (onFormSubmit) with the validated data; if validation fails, it populates the errors object instead and prevents form submission. this ensures that only valid data reaches your submission logic.
        handleSubmit,
        // formState is an object that contains information about the current state of the form, including any validation errors. In this case, we are destructuring the errors property from formState, which will hold any validation error messages generated by the zod schema when the form is submitted. This allows us to easily access and display error messages for each form field in the UI.
        formState: { errors }
    } = useForm<FormData>({ resolver: zodResolver(schema) })

    const onFormSubmit = (data: FieldValues) => {
        console.log(data)
    }

    return (
        <>
            <div className="flex h-screen justify-center items-center w-full bg-gray-200">
                <form
                    className="w-1/3 rounded-lg bg-white p-6 flex flex-col gap-4"
                    onSubmit={handleSubmit(onFormSubmit)}
                >
                    <h1 className="text-3xl font-bold mb-3">Login</h1>
                    <div className="flex flex-col">
                        <label htmlFor="email">Email</label>
                        <input
                            id="email"
                            className="bg-gray-200 px-4 py-2 rounded-lg"
                            {...register('email')}
                        />
                        {errors.email && (
                            <p className="text-red-500">
                                {errors.email.message}
                            </p>
                        )}
                    </div>

                    <div className="flex flex-col">
                        <label htmlFor="password">Password</label>
                        <input
                            id="password"
                            type="password"
                            className="bg-gray-200 px-4 py-2 rounded-lg"
                            {...register('password')}
                        />
                        {errors.password && (
                            <p className="text-red-500">
                                {errors.password.message}
                            </p>
                        )}
                    </div>

                    <button className="bg-gray-900 text-white px-6 py-4 text-xl font-medium w-full rounded-lg hover:bg-gray-700 disabled:hover:bg-gray-900 disabled:opacity-60">
                        Sign In
                    </button>
                </form>
            </div>
        </>
    )
}

export default App
